APPLICATION=shell

BOARD ?= olimex-stm32-p405

RIOTBASE ?= $(CURDIR)/../../../RIOT

USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps
USEMODULE += hts221

include $(RIOTBASE)/Makefile.include
