APPLICATION=timers

BOARD ?= olimex-stm32-p405 

USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps

RIOTBASE ?= $(CURDIR)/../../../RIOT

DEVELHELP ?= 1

include $(RIOTBASE)/Makefile.include
